version: '3.7'

services:
  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Хранение данных Postgres

  app:
    build: .
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://postgres:password@database:5432/mydb
    networks:
      - mynetwork
    command: npm run start  # Запускаем приложение без Nodemon
    volumes:
      - .:/app  # Монтируем локальную директорию в контейнер
      - /app/node_modules  # Исключаем node_modules, чтобы они не перетирались

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data: